version: '3'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    ports:
      - '8001:8001'
    environment:
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]